# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Ubuntu as a parent image
FROM ubuntu:22.04

# Set environment variables to non-interactive for package installations
ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libncurses-dev \
    bison \
    flex \
    libssl-dev \
    libelf-dev \
    libudev-dev \
    libpci-dev \
    libiberty-dev \
    && apt-get clean

# Set the working directory inside the container
WORKDIR /usr/src/linux

# Copy the entire kernel source into the container
COPY . .

# Build the kernel
RUN make defconfig && make -j$(nproc)

# Install modules
RUN make modules_install

# Clean up
RUN apt-get remove -y bison flex && apt-get autoremove -y

# Default command
CMD ["bash"]
